language: objective-c
osx_image: xcode7.2
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example

script:
#- xcodebuild -workspace Example/SwiftyDefaults.xcworkspace -scheme SwiftyDefaults-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- set -o pipefail
- xcodebuild -workspace Example/SwiftyDefaults.xcworkspace -scheme SwiftyDefaults-Example -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
